sudo: true
language: php
php:
  - 7.2
  - 7.1
  - nightly
env:
  - NODE_RELEASE=9.x
  - NODE_RELEASE=10.x

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  apt: true
  yarn: true
  composer: true
  directories:
    - site/vendor
    - site/web/app/themes/sd-theme/vendor
    - site/web/app/mu-plugins/skin-deep/vendor
    - site/web/app/themes/sd-theme/node_modules
    - site/web/app/mu-plugins/skin-deep/node_modules
addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.yarnpkg.com/debian/ stable main'
        key_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
      - sourceline: 'deb https://deb.nodesource.com/node_${NODE_RELEASE} stable main'
        key_url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
    packages:
      - yarn
      - nodejs

before_install:
  # Ensure bedrock is ready
  - cd site
  - phpenv config-rm xdebug.ini || true
  - composer self-update

install:
  - composer install -o --prefer-dist --no-interaction
  - yarn --cwd web/app/themes/sd-theme install
  - yarn --cwd web/app/mu-plugins/skin-deep install

script:
  - composer test
  - yarn --cwd web/app/themes/sd-theme run test
  - yarn --cwd web/app/mu-plugins/skin-deep run test
