sudo: true
language: php
php:
  - 7.2
  - 7.1
  - nightly
env:
  - NODE_RELEASE=9.x
  - NODE_RELEASE=10.x

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  apt: true
  yarn: true
  composer: true
  directories:
    - site/vendor
    - site/web/app/themes/sd-theme/vendor
    - site/web/app/mu-plugins/skin-deep/vendor
    - site/web/app/themes/sd-theme/node_modules
    - site/web/app/mu-plugins/skin-deep/node_modules

before_install:
  # Repo for newer Node.js versions
  - sudo rm -rf ~/.nvm
  - curl -sL https://deb.nodesource.com/setup_${NODE_RELEASE} | sudo -E bash -
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  # Install yarn and node
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq nodejs yarn
  # Ensure bedrock is ready
  - cd site
  - phpenv config-rm xdebug.ini || true
  - composer self-update

install:
  - composer install -o --prefer-dist --no-interaction
  - yarn --cwd web/app/themes/sd-theme install
  - yarn --cwd web/app/mu-plugins/skin-deep install

script:
  - composer test
  - yarn --cwd web/app/themes/sd-theme run test
  - yarn --cwd web/app/mu-plugins/skin-deep run test
