# State version
version: 2.1
commands:
  composer:
    description: "Install composer dependencies"
    parameters:
      path:
        description: directory containing composer.json
        type: string
    steps:
      - run: composer install --working-dir=<< parameters.path >> -o --no-progress --prefer-dist --no-interaction
  yarn-build:
    description: "Yarn: install and build"
    parameters:
      path:
        description: directory containing yarn.lock
        type: string
    steps:
      - yarn --cwd << parameters.path >> install
      - yarn --cwd << parameters.path >> build
jobs:
  # Install php dependencies
  install-php:
    docker:
      - image: php:7.3-alpine
    steps:
      # Now checkout the code
      - checkout:
          path: /src
      # Install composer
      - run: apk add --no-progress composer
      # Install bedrock dependencies
      - composer:
          path: /src/site
      # Install plugin dependencies
      - composer:
          path: /src/site/web/app/plugins/skin-deep
      # Install theme dependencies
      - composer:
          path: /src/site/web/app/themes/sd-theme
      # Save the install to the workspace
      - persist_to_workspace:
          root: /src/site
          paths:
            - web/
            - tests/
            - composer.*
            - phpcs.xml
            - phpstan.neon
            - vendor/
            - config/

  # Install/build frontend deps
  install-frontend:
    working_directory: /src
    docker:
      - image: node:10-stretch
    steps:
      # Get the pre-built php app
      - attach_workspace:
          at: .
      - yarn-build:
          path: web/app/plugins/skin-deep
      - yarnd-build:
          path: web/app/themes/sd-theme
      # Save the install to the workspace
      - persist_to_workspace:
          root: /src
          paths:
            - web/
            - tests/
            - composer.*
            - phpcs.xml
            - phpstan.neon
            - vendor/
            - config/

  # Test php
  check-php:
    working_directory: /src
    docker:
      - image: php:7.3-alpine
    steps:
      # Get the pre-built app
      - attach_workspace:
          at: .
      # Install composer again
      - run: apk add --no-progress composer
      # Run test
      - run: composer check

  # Run e2e tests
  e2e:
    machine: true
    steps:
      # Get the pre-built app
      - attach_workspace:
          at: .
      - run: sudo apt-get update && sudo apt-get install tree
      - run: tree ./web -d -L 5
      - run:
          command: docker-compose build
          working_directory: tests
      - run:
          command: docker-compose up --abort-on-container-exit --exit-code-from cypress
          working_directory: tests
      - store_artifacts:
          path: ./tests/cypress/screenshots
      - store_artifacts:
          path: ./tests/cypress/videos

  # Test plugin deps
  test-plugin:
    working_directory: /src
    docker:
      - image: node:10-stretch
    steps:
      # Get the pre-built php app
      - attach_workspace:
          at: .
      - run: yarn --cwd web/app/mu-plugins/skin-deep test

  # Test theme deps
  test-theme:
    working_directory: /src
    docker:
      - image: node:10-stretch
    steps:
      # Get the pre-built php app
      - attach_workspace:
          at: .
      - run: yarn --cwd web/app/themes/sd-theme test

workflows:
  version: 2
  web:
    jobs:
      - install-php
      - install-frontend:
          requires:
            - install-php
      - check-php:
          requires:
            - install-php
      - e2e:
          requires:
            - install-frontend
      - test-plugin:
          requires:
            - install-frontend
      - test-theme:
          requires:
            - install-frontend
