# State version
version: 2.0
jobs:
  # Install php dependencies
  install-php:
    docker:
      - image: php:7.3-alpine
    steps:
      # Now checkout the code
      - checkout:
          path: /src
      # Install composer
      - run: apk add --no-progress composer
      # Install bedrock dependencies
      - run:
          name: Install bedrock dependencies
          command: composer install -o --no-progress --prefer-dist --no-interaction
          working_directory: /src/site
      # Install plugin dependencies
      - run:
          name: Install plugin dependencies
          command: composer install -o --no-progress --prefer-dist --no-interaction
          working_directory: /src/site/web/app/mu-plugins/skin-deep
      # Install theme dependencies
      - run:
          name: Install theme dependencies
          command: composer install -o --no-progress --prefer-dist --no-interaction
          working_directory: /src/site/web/app/themes/sd-theme
      # Save the install to the workspace
      - persist_to_workspace:
          root: /src/site
          paths:
            - web/
            - tests/
            - composer.*
            - phpcs.xml
            - phpstan.neon
            - vendor/
            - config/

  # Test php
  check-php:
    working_directory: /app
    docker:
      - image: php:7.3-alpine
    steps:
      # Get the pre-built app
      - attach_workspace:
          at: .
      # Install composer again
      - run: apk add --no-progress composer
      # Run test
      - run: composer check

  analyse-php:
    working_directory: /app
    docker:
      - image: php:7.3-alpine
        environment:
          DB_USER: root
          DB_PASSWORD: root
          DB_HOST: 127.0.0.1
          DB_NAME: ci_development
      - image: mariadb:10.2
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ci_development
    steps:
      # Get the pre-built app
      - attach_workspace:
          at: .
      # Install php deps
      - run: apk add --no-progress libpng-dev libxml2-dev libzip-dev composer git
      # Install php deps
      - run: docker-php-ext-install gd mysqli opcache xmlrpc zip
      # Install wp cli
      - run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          mv wp-cli.phar /usr/local/bin/wp
      # Install wp tables
      - run:
          command: wp --allow-root core install --url=skindeepmag.com --title=example --admin_user=admin --admin_email=admin@example.com
          working_directory: web
      # Activate theme
      - run:
          command: wp --allow-root theme activate sd-theme/resources
          working_directory: web
      # Run analysis
      - run: composer analyse -- --no-progress --no-interaction --memory-limit=4G

  # Test plugin deps
  frontend-plugin:
    working_directory: /app
    docker:
      - image: node:10-stretch
    steps:
      - checkout
      - run: yarn --cwd site/web/app/mu-plugins/skin-deep install
      - run: yarn --cwd site/web/app/mu-plugins/skin-deep test

  # Test theme deps
  frontend-theme:
    working_directory: /app
    docker:
      - image: node:10-stretch
    steps:
      - checkout
      - run: yarn --cwd site/web/app/themes/sd-theme install
      - run: yarn --cwd site/web/app/themes/sd-theme test

workflows:
  version: 2
  web:
    jobs:
      - install-php
      - check-php:
          requires:
            - install-php
      - analyse-php:
          requires:
            - install-php
  frontend:
    jobs:
      - frontend-plugin
      - frontend-theme