# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  skindeepmag.com:
    nginx_wordpress_site_conf: "{{ skindeepmag_com_nginx_conf }}"
    site_hosts:
      - canonical: skindeepmag.com
        redirects:
          - www.skindeepmag.com
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:briggySmalls/skin-deep-server.git
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
      duration: 30s
      skip_cache_uri: /wp-admin/|/xmlrpc.php|wp-.*.php|/feed/|index.php|sitemap(_index)?.xml
      skip_cache_cookie: comment_author|wordpress_[a-f0-9]+|wp-postpass|wordpress_no_cache|wordpress_logged_in
    env:
      acf_pro_key: "{{ vault_acf_pro_key }}"
      google_tracking_id: "{{ skindeepmag_com_google_tracking_id }}"


